# Generated by Django 3.2.6 on 2021-08-07 18:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210804_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2021, 8, 7, 18, 31, 48, 678867, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='details',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2021, 8, 7, 18, 31, 48, 678867, tzinfo=utc)),
        ),
    ]
